name: Check

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Check the YAML in .github and containers
        run: |
          docker run \
            --rm \
            --volume "$(pwd):/work" \
            backplane/yamllint \
              -f github \
              .
