name: Docker
on:
  push:
    branches:
    - main
    tags:
    - v*.*.*
  pull_request:
  schedule:
  - cron: "16 9 * * *"
env:
  DH_USER: galvanist
jobs:
  buildpush:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container:
        - "7z"
        - "adb"
        - "apg"
        - "audiosprite"
        - "black"
        - "blampy"
        - "bpython"
        - "chardet"
        - "checkmake"
        - "chrome"
        - "compose_sort"
        - "firefox"
        - "fzf"
        - "ghlatest"
        - "goenv"
        - "graphviz"
        - "grta"
        - "haskellenv"
        - "httpie"
        - "hugo"
        - "jq"
        - "json-server"
        - "kotlinc"
        - "kp1p"
        - "lxde"
        - "mssql-cli"
        - "mssql-scripter"
        - "myip"
        - "mypy"
        - "ods_conv"
        - "pdf"
        - "pwgen"
        - "pycodestyle"
        - "pygmentize"
        - "pylint"
        - "qrencode"
        - "shunit2"
        - "snakeeyes"
        - "sql-formatter"
        - "tsqllint"
        - "vueenv"
        - "wimlib-imagex"
        - "wireguard"
        - "wpa_passphrase"
        - "youtube-dl"
    if: github.event_name == 'push' || github.event_name == 'schedule'
    steps:
    - uses: actions/checkout@v2
    - name: Dual Registry Login
      run: |
        # github
        printf '%s' "${{ secrets.GITHUB_TOKEN }}" | docker login --username "${{ github.actor }}" --password-stdin docker.pkg.github.com
        # docker hub
        printf '%s' '${{ secrets.DOCKER_HUB_TOKEN }}' | docker login --username "$DH_USER" --password-stdin
    - name: Build push
      run: |
        export GH_REGISTRY_PATH="docker.pkg.github.com/${{ github.repository }}"
        export DH_REGISTRY_PATH="galvanist/conex"
        .helpers/maker.sh build ${{ matrix.container }}
        .helpers/maker.sh postbuild ${{ matrix.container }}
        .helpers/maker.sh ghpush ${{ matrix.container }}
        .helpers/maker.sh dhpush ${{ matrix.container }}
        .helpers/maker.sh postpush ${{ matrix.container }}
